/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh_project;

import ktdh_project.AllPanel.PanelDraw3D;
import ktdh_project.AllPanel.PanelDraw2D;
import ktdh_project.AllPanel.PanelAction2D;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;


/**
 *
 * @author nguye
 */
public class Pattern extends javax.swing.JFrame {

    /**
     * Creates new form Pattern
     */
    public Pattern() {
        initComponents();
//        resetAll();
        this.setSize(1500, 1000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInput = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        jPanelFunction = new javax.swing.JPanel();
        jButtonDraw2D = new javax.swing.JButton();
        jButtonAction2D = new javax.swing.JButton();
        jButtonDraw3D = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButtonExit = new javax.swing.JButton();
        jPanelShow = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInput.setBackground(java.awt.SystemColor.controlDkShadow);
        jPanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelInput.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, -1, -1));

        jPanelFunction.setBackground(java.awt.SystemColor.controlShadow);
        jPanelFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDraw2D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonDraw2D.setText("Vẽ 2D");
        jButtonDraw2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDraw2DActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonDraw2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 36, 100, 50));

        jButtonAction2D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonAction2D.setText("Cảnh 2D");
        jButtonAction2D.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAction2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAction2DActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonAction2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 36, 100, 50));

        jButtonDraw3D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonDraw3D.setText("Vẽ 3D");
        jButtonDraw3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDraw3DActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonDraw3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 36, 100, 50));
        jPanelFunction.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 0, -1, -1));
        jPanelFunction.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 62, 11, -1));

        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonExit.setText("Thoát");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 36, 100, 50));

        jPanelShow.setBackground(new java.awt.Color(204, 204, 204));

        jLabelWelcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(0, 0, 255));
        jLabelWelcome.setText("PHẦN MỀM KỸ THUẬT ĐỒ HỌA NHÓM 7");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("Thành viên nhóm 7:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Trần Quốc Bảo - N18DCCN013");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Nguyễn Thanh Duy - N18DCCN031");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nguyễn Thanh Hiền - N18DCCN061");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Đỗ Duy Khang - N18DCCN091");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Nguyễn Quốc Thắng - N18DCCN211");

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addGroup(jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelWelcome)
                        .addGroup(jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelShowLayout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelShowLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(171, 171, 171))))
                    .addGroup(jPanelShowLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addGroup(jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabelWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDraw2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDraw2DActionPerformed
        setDraw2D();
//        resetDraw2D();
//        resetTextField();
        
    }//GEN-LAST:event_jButtonDraw2DActionPerformed

    private void jButtonDraw3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDraw3DActionPerformed
        setDraw3D();
//        resetDraw3D();
//        resetTextField();
        
    }//GEN-LAST:event_jButtonDraw3DActionPerformed

    private void jButtonAction2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAction2DActionPerformed
        setAction2D();
//        resetAction2D();
//        resetTextField();
        
    }//GEN-LAST:event_jButtonAction2DActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void reloadScreen(){
        jPanelInput.removeAll();
        jPanelShow.removeAll();
        jPanelShow.setVisible(false);
        jPanelShow.setVisible(true);
    }
    
    public void setDraw2D(){
        reloadScreen();
        PanelDraw2D panel = new PanelDraw2D();
        jPanelInput.setLayout(new BorderLayout());
        jPanelInput.add(panel.getComponent(0));
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(panel.getComponent(0));
        jPanelShow.validate();
        jPanelInput.validate();
        System.out.print(1);
    }
    
    public void setDraw3D(){
        reloadScreen();
        PanelDraw3D panel = new PanelDraw3D();
        jPanelInput.setLayout(new BorderLayout());
        jPanelInput.add(panel.getComponent(0));
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(panel.getComponent(0));
        jPanelInput.validate();
        jPanelShow.validate();
    }
    
        public void setAction2D(){
        reloadScreen();
        PanelAction2D panel = new PanelAction2D();
        jPanelInput.setLayout(new BorderLayout());
        jPanelInput.add(panel.getComponent(0));
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(panel.getComponent(0));
        jPanelInput.validate();
        jPanelShow.validate();
    }
    
    public void checkNumberType(KeyEvent evt){
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE) ||
            (c == KeyEvent.VK_MINUS))) {
            getToolkit().beep();
            evt.consume();
        }
    }
    
    
    public void showInput(){
        
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pattern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonAction2D;
    private javax.swing.JButton jButtonDraw2D;
    private javax.swing.JButton jButtonDraw3D;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelFunction;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
