/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh_project;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;

/**
 *
 * @author nguye
 */
public class Pattern extends javax.swing.JFrame {

    /**
     * Creates new form Pattern
     */
    public Pattern() {
        initComponents();
        resetAll();
        this.setSize(1500, 1000);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInput = new javax.swing.JPanel();
        jTextFieldX = new javax.swing.JTextField();
        jLabelX = new javax.swing.JLabel();
        jLabelY = new javax.swing.JLabel();
        jLabelZ = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jTextFieldZ = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        jButtonDraw = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jPanelFunction = new javax.swing.JPanel();
        jButtonDraw2D = new javax.swing.JButton();
        jButtonAction2D = new javax.swing.JButton();
        jButtonDraw3D = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButtonExit = new javax.swing.JButton();
        jPanelShow = new javax.swing.JPanel();
        jLabelWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInput.setBackground(java.awt.SystemColor.controlDkShadow);
        jPanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldXKeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldX, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 102, -1));

        jLabelX.setText("X");
        jPanelInput.add(jLabelX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabelY.setText("Y");
        jPanelInput.add(jLabelY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabelZ.setText("Z");
        jPanelInput.add(jLabelZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jTextFieldY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldYKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldYKeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 102, -1));

        jTextFieldZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZActionPerformed(evt);
            }
        });
        jTextFieldZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldZKeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 103, -1));
        jPanelInput.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, -1, -1));

        jButtonDraw.setText("Draw");
        jPanelInput.add(jButtonDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jButtonClear.setText("Clear");
        jPanelInput.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jPanelFunction.setBackground(java.awt.SystemColor.controlShadow);
        jPanelFunction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDraw2D.setText("Draw 2D");
        jButtonDraw2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDraw2DActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonDraw2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 36, 100, 50));

        jButtonAction2D.setText("Action 2D");
        jButtonAction2D.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAction2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAction2DActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonAction2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 36, 100, 50));

        jButtonDraw3D.setText("Draw 3D");
        jButtonDraw3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDraw3DActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonDraw3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 36, 100, 50));
        jPanelFunction.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 0, -1, -1));
        jPanelFunction.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 62, 11, -1));

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        jPanelFunction.add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 36, 100, 50));

        jPanelShow.setBackground(new java.awt.Color(255, 255, 255));

        jLabelWelcome.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelWelcome.setForeground(new java.awt.Color(0, 255, 0));
        jLabelWelcome.setText("PHẦN MỀM KỸ THUẬT ĐỒ HỌA NHÓM 7");

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabelWelcome)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabelWelcome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDraw2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDraw2DActionPerformed
        resetDraw2D();
        resetTextField();
        setDraw2D();
    }//GEN-LAST:event_jButtonDraw2DActionPerformed

    private void jButtonDraw3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDraw3DActionPerformed
        resetDraw3D();
        resetTextField();
        setDraw3D();
    }//GEN-LAST:event_jButtonDraw3DActionPerformed

    private void jButtonAction2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAction2DActionPerformed
        resetAction2D();
        resetTextField();
        setAction2D();
    }//GEN-LAST:event_jButtonAction2DActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextFieldZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZActionPerformed

    private void jTextFieldXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldXKeyTyped
        // TODO add your handling code here:
        checkNumberType(evt);
        
    }//GEN-LAST:event_jTextFieldXKeyTyped

    private void jTextFieldYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldYKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldYKeyPressed

    private void jTextFieldYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldYKeyTyped
        // TODO add your handling code here:
        checkNumberType(evt);
    }//GEN-LAST:event_jTextFieldYKeyTyped

    private void jTextFieldZKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldZKeyTyped
        // TODO add your handling code here:
        checkNumberType(evt);
    }//GEN-LAST:event_jTextFieldZKeyTyped

    /**
     * @param args the command line arguments
     */
    public void setDraw2D(){
        jPanelShow.removeAll();
        jPanelShow.setSize(800,800);
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(new MyCanvas());
        jPanelShow.validate();
    }
    
    public void setDraw3D(){
        jPanelShow.removeAll();
        JPanel newPanel = new JPanel();
        jPanelShow.add(newPanel);
        // ve truc 3D
        jPanelShow.validate();
    }
    
    public void checkNumberType(KeyEvent evt){
        char c = evt.getKeyChar();
      if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
        getToolkit().beep();
        evt.consume();
      }
    }
    
    public void setAction2D(){
        jPanelShow.removeAll();
        JPanel newPanel = new JPanel();
        jPanelShow.add(newPanel);
        jPanelShow.validate();
    }
    
    public void showInput(){
        
    }
    
    public void reset(){
        jLabelX.setVisible(false);
        jLabelY.setVisible(false);
        jLabelZ.setVisible(false);
        jTextFieldX.setVisible(false);
        jTextFieldY.setVisible(false);
        jTextFieldZ.setVisible(false);
    }
    
    public void resetTextField(){
        jTextFieldX.setText("");
        jTextFieldY.setText("");
        jTextFieldZ.setText("");
    }
    
    public void resetAll(){
        reset();
        jLabelWelcome.setVisible(true);
    }
    
    public void resetAction2D(){
        reset();
        jLabelWelcome.setVisible(false);
    }
    
    public void resetDraw2D(){
        jLabelX.setVisible(true);
        jLabelY.setVisible(true);
        jLabelZ.setVisible(false);
        jTextFieldX.setVisible(true);
        jTextFieldY.setVisible(true);
        jTextFieldZ.setVisible(false);
    }
    
    public void resetDraw3D(){
        jLabelX.setVisible(true);
        jLabelY.setVisible(true);
        jLabelZ.setVisible(true);
        jTextFieldX.setVisible(true);
        jTextFieldY.setVisible(true);
        jTextFieldZ.setVisible(true);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pattern.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pattern().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonAction2D;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JButton jButtonDraw2D;
    private javax.swing.JButton jButtonDraw3D;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JLabel jLabelZ;
    private javax.swing.JPanel jPanelFunction;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    private javax.swing.JTextField jTextFieldZ;
    // End of variables declaration//GEN-END:variables
}
