/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh_project.AllPanel;

import java.awt.BorderLayout;
import ktdh_project.LineMode;
import ktdh_project.MyCanvas;
import ktdh_project.MyLibrary;
import ktdh_project.Point2D;

/**
 *
 * @author Tran Quoc Bao
 */
public class PanelDraw2D extends javax.swing.JPanel {

    /**
     * Creates new form PanelDraw2D
     */
    public PanelDraw2D() {
        initComponents();
        setDraw2D();
    }
    
    
    public void setDraw2D(){
        jPanelShow.removeAll();
        jPanelShow.setSize(800,800);
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(new MyCanvas());
        jPanelShow.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInput = new javax.swing.JPanel();
        jLabelX2 = new javax.swing.JLabel();
        jLabelY2 = new javax.swing.JLabel();
        jTextFieldX2 = new javax.swing.JTextField();
        jTextFieldY2 = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        jButtonDraw = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelY1 = new javax.swing.JLabel();
        jTextFieldY1 = new javax.swing.JTextField();
        jTextFieldX1 = new javax.swing.JTextField();
        jLabelX1 = new javax.swing.JLabel();
        jPanelShow = new javax.swing.JPanel();

        jPanelInput.setBackground(java.awt.SystemColor.controlDkShadow);
        jPanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelX2.setText("X2");
        jPanelInput.add(jLabelX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabelY2.setText("Y2");
        jPanelInput.add(jLabelY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jTextFieldX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldX2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldX2KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 102, -1));

        jTextFieldY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldY2ActionPerformed(evt);
            }
        });
        jTextFieldY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldY2KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 103, -1));
        jPanelInput.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, -1, -1));

        jButtonDraw.setText("Vẽ");
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrawActionPerformed(evt);
            }
        });
        jPanelInput.add(jButtonDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 60, -1));

        jButtonClear.setText("Xóa");
        jPanelInput.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 60, -1));

        jLabelY1.setText("Y1");
        jPanelInput.add(jLabelY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jTextFieldY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldY1KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 102, -1));

        jTextFieldX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldX1KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 102, -1));

        jLabelX1.setText("X1");
        jPanelInput.add(jLabelX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanelShow.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldX1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX1KeyTyped

    private void jTextFieldY1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldY1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY1KeyTyped

    private void jButtonDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrawActionPerformed
        // TODO add your handling code here:
        draw2DLine(LineMode.DASH);
    }//GEN-LAST:event_jButtonDrawActionPerformed

    private void jTextFieldY2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldY2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY2KeyTyped

    private void jTextFieldY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY2ActionPerformed

    private void jTextFieldX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldX2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX2KeyTyped

    private void jTextFieldX2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldX2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX2KeyPressed

        public void draw2DLine(LineMode mode){
        int x1 = Integer.parseInt(jTextFieldX1.getText());
        int y1 = Integer.parseInt(jTextFieldY1.getText());
        int x2 = Integer.parseInt(jTextFieldX2.getText());
        int y2 = Integer.parseInt(jTextFieldY2.getText());
        Point2D startPoint = new Point2D(x1, y1);
        Point2D endPoint = new Point2D(x2, y2);
        MyLibrary.drawLine2D(startPoint, endPoint, mode ,jPanelShow);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JLabel jLabelX1;
    private javax.swing.JLabel jLabelX2;
    private javax.swing.JLabel jLabelY1;
    private javax.swing.JLabel jLabelY2;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldX2;
    private javax.swing.JTextField jTextFieldY1;
    private javax.swing.JTextField jTextFieldY2;
    // End of variables declaration//GEN-END:variables
}

