/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh_project.AllPanel;

/**
 *
 * @author Tran Quoc Bao
 */
public class PanelDraw3D extends javax.swing.JPanel {

    /**
     * Creates new form PanelDraw3D
     */
    public PanelDraw3D() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInput = new javax.swing.JPanel();
        jLabelX2 = new javax.swing.JLabel();
        jLabelY2 = new javax.swing.JLabel();
        jTextFieldX2 = new javax.swing.JTextField();
        jTextFieldY2 = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        jButtonDraw = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelY1 = new javax.swing.JLabel();
        jTextFieldY1 = new javax.swing.JTextField();
        jTextFieldX1 = new javax.swing.JTextField();
        jLabelX1 = new javax.swing.JLabel();
        jLabelZ1 = new javax.swing.JLabel();
        jTextFieldZ1 = new javax.swing.JTextField();
        jLabelZ2 = new javax.swing.JLabel();
        jTextFieldZ2 = new javax.swing.JTextField();
        jPanelShow = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jPanelInput.setBackground(java.awt.SystemColor.controlDkShadow);
        jPanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelX2.setText("X2");
        jPanelInput.add(jLabelX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabelY2.setText("Y2");
        jPanelInput.add(jLabelY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jTextFieldX2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldX2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldX2KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 102, -1));

        jTextFieldY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldY2ActionPerformed(evt);
            }
        });
        jTextFieldY2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldY2KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 103, -1));
        jPanelInput.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, -1, -1));

        jButtonDraw.setText("Vẽ");
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrawActionPerformed(evt);
            }
        });
        jPanelInput.add(jButtonDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 60, -1));

        jButtonClear.setText("Xóa");
        jPanelInput.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 60, -1));

        jLabelY1.setText("Y1");
        jPanelInput.add(jLabelY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jTextFieldY1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldY1KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 102, -1));

        jTextFieldX1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldX1KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 102, -1));

        jLabelX1.setText("X1");
        jPanelInput.add(jLabelX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabelZ1.setText("Z1");
        jPanelInput.add(jLabelZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jTextFieldZ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldZ1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldZ1KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldZ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 102, -1));

        jLabelZ2.setText("Z2");
        jPanelInput.add(jLabelZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jTextFieldZ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldZ2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldZ2KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextFieldZ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 102, -1));

        jPanelShow.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("3D");

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(jButton1)
                .addContainerGap(529, Short.MAX_VALUE))
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelShowLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldX2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldX2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX2KeyPressed

    private void jTextFieldX2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldX2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX2KeyTyped

    private void jTextFieldY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY2ActionPerformed

    private void jTextFieldY2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldY2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY2KeyTyped

    private void jButtonDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDrawActionPerformed

    private void jTextFieldY1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldY1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldY1KeyTyped

    private void jTextFieldX1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldX1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldX1KeyTyped

    private void jTextFieldZ1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldZ1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZ1KeyPressed

    private void jTextFieldZ1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldZ1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZ1KeyTyped

    private void jTextFieldZ2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldZ2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZ2KeyPressed

    private void jTextFieldZ2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldZ2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZ2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JLabel jLabelX1;
    private javax.swing.JLabel jLabelX2;
    private javax.swing.JLabel jLabelY1;
    private javax.swing.JLabel jLabelY2;
    private javax.swing.JLabel jLabelZ1;
    private javax.swing.JLabel jLabelZ2;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JTextField jTextFieldX1;
    private javax.swing.JTextField jTextFieldX2;
    private javax.swing.JTextField jTextFieldY1;
    private javax.swing.JTextField jTextFieldY2;
    private javax.swing.JTextField jTextFieldZ1;
    private javax.swing.JTextField jTextFieldZ2;
    // End of variables declaration//GEN-END:variables
}
