/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktdh_project.AllPanel;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import ktdh_project.Class3D.Draw3D;
import ktdh_project.Class3D.MyCanvas3D;
import ktdh_project.Class3D.Point3D;

/**
 *
 * @author Tran Quoc Bao
 */
public class PanelDraw3D extends javax.swing.JPanel {

    /**
     * Creates new form PanelDraw3D
     */
    public PanelDraw3D() {
        initComponents();
        setStart();
        setDraw3D();
    }
    private int mode = 0; // if mode == 0: draw rectangle box, else cylinder
    
    public void setMode(int mode){
        this.mode = mode;
    }
    
    public int getMode(){
        return this.mode;
    }
    
    
        public void setDraw3D(){
        jPanelShow.removeAll();
        jPanelShow.setSize(1000,1000);
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(new MyCanvas3D());
        jPanelShow.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInput = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 0), new java.awt.Dimension(120, 32767));
        jButtonCycl = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        JTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonRect = new javax.swing.JButton();
        jButtonDraw = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        JTfRootX = new javax.swing.JTextField();
        jLbRootX = new javax.swing.JLabel();
        jLbRootY = new javax.swing.JLabel();
        JTfRootY = new javax.swing.JTextField();
        jTfRootZ = new javax.swing.JTextField();
        jLbRootZ = new javax.swing.JLabel();
        jLbRoot = new javax.swing.JLabel();
        jPanelShow = new javax.swing.JPanel();

        jPanelInput.setBackground(java.awt.SystemColor.controlDkShadow);
        jPanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelInput.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 375, -1, -1));

        jButtonCycl.setText("Hình trụ");
        jButtonCycl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCyclActionPerformed(evt);
            }
        });
        jPanelInput.add(jButtonCycl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 140, -1));

        jButtonClear.setText("Xóa");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanelInput.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 60, -1));

        JTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField1ActionPerformed(evt);
            }
        });
        JTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextField1KeyTyped(evt);
            }
        });
        jPanelInput.add(JTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, -1));

        jLabel1.setText("X");
        jPanelInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel2.setText("Y");
        jPanelInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        JTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTextField2KeyTyped(evt);
            }
        });
        jPanelInput.add(JTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 100, -1));

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        jPanelInput.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        jLabel3.setText("Z");
        jPanelInput.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jButtonRect.setText("Hình hộp chữ nhật");
        jButtonRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRectActionPerformed(evt);
            }
        });
        jPanelInput.add(jButtonRect, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, -1));

        jButtonDraw.setText("Vẽ");
        jButtonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrawActionPerformed(evt);
            }
        });
        jPanelInput.add(jButtonDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 60, -1));
        jPanelInput.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 140, -1));
        jPanelInput.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 140, -1));

        JTfRootX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTfRootXKeyTyped(evt);
            }
        });
        jPanelInput.add(JTfRootX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 100, -1));

        jLbRootX.setText("X");
        jPanelInput.add(jLbRootX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLbRootY.setText("Y");
        jPanelInput.add(jLbRootY, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        JTfRootY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTfRootYKeyTyped(evt);
            }
        });
        jPanelInput.add(JTfRootY, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, -1));

        jTfRootZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTfRootZKeyTyped(evt);
            }
        });
        jPanelInput.add(jTfRootZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, -1));

        jLbRootZ.setText("Z");
        jPanelInput.add(jLbRootZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLbRoot.setText("Tâm");
        jPanelInput.add(jLbRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jPanelShow.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelShowLayout = new javax.swing.GroupLayout(jPanelShow);
        jPanelShow.setLayout(jPanelShowLayout);
        jPanelShowLayout.setHorizontalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
        jPanelShowLayout.setVerticalGroup(
            jPanelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jPanelShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCyclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCyclActionPerformed
        setCylinder();
    }//GEN-LAST:event_jButtonCyclActionPerformed

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        checkOnlyNumber(evt, false);

    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButtonRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRectActionPerformed
        // TODO add your handling code here:
        setRectangleBox();
    }//GEN-LAST:event_jButtonRectActionPerformed

    private void JTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField2KeyTyped
        // TODO add your handling code here:
        checkOnlyNumber(evt, false);
    }//GEN-LAST:event_JTextField2KeyTyped

    private void JTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTextField1KeyTyped
        // TODO add your handling code here:
        checkOnlyNumber(evt, false);
    }//GEN-LAST:event_JTextField1KeyTyped

    private void jButtonDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrawActionPerformed
        // TODO add your handling code here:
        try{
            if(getMode() == 0){
            drawRectBox();
            }
            else{
                drawCylinder();
            }
        }
        catch(Exception ex){
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ hoặc nhập sai thông số.");
        }
        
    }//GEN-LAST:event_jButtonDrawActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void JTfRootXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTfRootXKeyTyped
        checkOnlyNumber(evt, true);
    }//GEN-LAST:event_JTfRootXKeyTyped

    private void JTfRootYKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTfRootYKeyTyped
        checkOnlyNumber(evt, true);
    }//GEN-LAST:event_JTfRootYKeyTyped

    private void jTfRootZKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfRootZKeyTyped
        checkOnlyNumber(evt, true);
    }//GEN-LAST:event_jTfRootZKeyTyped

    private void JTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextField1ActionPerformed
    
    public void checkOnlyNumber(KeyEvent evt, boolean positive){
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE) ||
            ((c == KeyEvent.VK_MINUS) && positive))) {
            getToolkit().beep();
            evt.consume();
        }
    }
    
    public void setCylinder(){
        setMode(1);
        showRootInput();
        jButtonClear.setVisible(true);
        jButtonDraw.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        JTextField1.setVisible(true);
        JTextField2.setVisible(true);
        jLabel3.setVisible(false);
        jTextField3.setVisible(false);
        jLabel1.setText("R");
        jLabel2.setText("H");
    }
    
    public void setRectangleBox(){
        setMode(0);
        showRootInput();
        jButtonClear.setVisible(true);
        jButtonDraw.setVisible(true);
        jLabel1.setVisible(true);
        jLabel2.setVisible(true);
        JTextField1.setVisible(true);
        JTextField2.setVisible(true);
        jLabel3.setVisible(true);
        jTextField3.setVisible(true);
        jLabel1.setText("CR");
        jLabel2.setText("CD");
        jLabel3.setText("CC");
    }
    
    public void setStart(){
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        JTextField1.setVisible(false);
        JTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jLbRootX.setVisible(false);
        jLbRootY.setVisible(false);
        jLbRootZ.setVisible(false);
        JTfRootX.setVisible(false);
        JTfRootY.setVisible(false);
        jTfRootZ.setVisible(false);
        jLbRoot.setVisible(false);
        jButtonClear.setVisible(false);
        jButtonDraw.setVisible(false);
   }
    
    public void showRootInput(){
        jLbRootX.setVisible(true);
        jLbRootY.setVisible(true);
        jLbRootZ.setVisible(true);
        JTfRootX.setVisible(true);
        JTfRootY.setVisible(true);
        jTfRootZ.setVisible(true);
        jLbRoot.setVisible(true);
    }
    
    public void drawRectBox(){
        int x = Integer.parseInt(JTextField1.getText());
        int y = Integer.parseInt(JTextField2.getText());
        int z = Integer.parseInt(jTextField3.getText());
        
        int rootX = Integer.parseInt(JTfRootX.getText());
        int rootY = Integer.parseInt(JTfRootY.getText());
        int rootZ = Integer.parseInt(jTfRootZ.getText());
        
        Draw3D.DrawRectangular(x, y, z,new Point3D(rootX, rootY, rootZ), jPanelShow);
    }
    
    public void drawCylinder(){
        int r = Integer.parseInt(JTextField1.getText());
        int h = Integer.parseInt(JTextField2.getText());
        
        int rootX = Integer.parseInt(JTfRootX.getText());
        int rootY = Integer.parseInt(JTfRootY.getText());
        int rootZ = Integer.parseInt(jTfRootZ.getText());
        
        Draw3D.DrawCylinder(r, h,new Point3D(rootX, rootY, rootZ), jPanelShow);
    }
    
    public void clear(){
        resetTextField();
        jPanelShow.removeAll();
        jPanelShow.setSize(800,800);
        jPanelShow.setLayout(new BorderLayout());
        jPanelShow.add(new MyCanvas3D());
        jPanelShow.validate();
    }
    
    public void resetTextField(){
        JTextField1.setText("");
        JTextField2.setText("");
        jTextField3.setText("");
        JTfRootX.setText("");
        JTfRootY.setText("");
        jTfRootZ.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField1;
    private javax.swing.JTextField JTextField2;
    private javax.swing.JTextField JTfRootX;
    private javax.swing.JTextField JTfRootY;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCycl;
    private javax.swing.JButton jButtonDraw;
    private javax.swing.JButton jButtonRect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbRoot;
    private javax.swing.JLabel jLbRootX;
    private javax.swing.JLabel jLbRootY;
    private javax.swing.JLabel jLbRootZ;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelShow;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTfRootZ;
    // End of variables declaration//GEN-END:variables
}
